### ISSUE TITLE
Identify Maven Plugins Goals

### ISSUE THREAD

**Issue by brunoborges** [Microsoft/vscode-maven#126]
Currently, the Maven view only lists the well-known Maven goals.

When plugins are added to the `pom.xml`, the View should identify what goals these plugins provide.

This is how the view looks like on VS Code: 
![image](https://user-images.githubusercontent.com/129743/45397993-4ab92f80-b5f7-11e8-9e7a-872f3150f943.png)

This is how the view looks like on IntelliJ: 
![image](https://user-images.githubusercontent.com/129743/45398010-5efd2c80-b5f7-11e8-963a-15c6196dfdd7.png)

**Comment by Eskibear** [comment]
My proposal is to:
1. Read plugin information from the effective pom.
2. Call `mvn help:describe` to retrieve the goals of a plugin.

It looks like the following:
![image](https://user-images.githubusercontent.com/2351748/49490386-c6d7b200-f88a-11e8-902e-39ad7f8ef614.png)

**Comment by Eskibear** [comment]
@fssrepository I find in IntelliJ IDEA, they show the dependency tree (only including those in compile scope). 
![image](https://user-images.githubusercontent.com/2351748/49785107-61883300-fd5a-11e8-8bd4-f7c61d3f6204.png)

We can also show a similar tree view in this Maven extension. And currently we just provide data to a tree view, if we want to support searching, we'll have to adopt the following API. I think technically it's feasible. 
https://github.com/Microsoft/vscode/blob/34f0b1876ca8164d6835da58cc0e3174cba5acf7/src/vs/vscode.d.ts#L6632-L6677

**Comment by fssrepository** [comment]
Referencing to the previous comment:
[https://github.com/Microsoft/vscode-maven/issues/161#issuecomment-446107445](url)

I have talked about dependency:tree menu item next to the effective pom. It's not a maven plugin responsibility, but the following would be quite handy.

1) At the moment I think mvn dependency:tree does not show the dependencies coming from the maven parent, and it does not show the plugin dependencies also.

2) The effective pom shows the parent dependencies also, but in a flat/non-transitive way.
I'm not sure how to achieve to step back on the parent tree, not only in the maven transitive dependency tree.

3) separating compile/test/runtime scopes in the tree

4) Multimodule scenario, where every child has the same parent and got the same versioning while building.

I personally feel if somebody really needs a pure effective pom or a dependency tree just run the command.

The effective pom menu item does not really add anything even for the convenience purpose, but if the 4 of the results would be combined in a tree in a filterable way somehow it would be a much more welcoming option. (filter can be some sort of regex by type - so half regex/half type)

For example:
At the moment there is a discussion about to improve the "Problems" tab - where there is a problem that I cannot filter "info" type inside a project. (multi-project workspace) As a developer, I was trying to think logically, and the first line was I tried is: **/project_name[info] - where the info was not the text, it was the type. - A similar approach might be introduced here also to filter out dependency types.

You can clone idea/eclipse/NetBeans, but the fact is, that after 15 years of development I simply don't use those frameworks.

The idea has too many menus, so I'm just wasting time to find the menus, and I was unable to really accommodate how the menus have been named after half year usage.

Eclipse was quite unstable on plugin front.

Netbeans is java based and the java based scrolling is lagging on Ubuntu 18.04.1 LTS.

I would urge to resolve some sort of problems also, which have never done before. I know the combination of the results would be a little bit robust approach, but it would really add up something against the command line options.

The real genuine thing would be, how to make the combined result less cluttered.

When I was developing maven apps, I think I missed the combined results, I was not really interested individually. Unfortunately, maven is a different project, which won't be changed, but I would have reduced the commands related to how to analyze dependencies.

In one company I wasted about 1,5 weeks to clean up the dependency tree because of lack of proper tool.

**Comment by Eskibear** [comment]
I'm closing it as the original feature has been implemented. 

For the dependency tree view feature request, there's already another issue #161 for it, let track it there.
