### ISSUE TITLE
Not able to chose the folder where saving the Maven project

### ISSUE THREAD

**Issue by ppatierno** [Microsoft/vscode-maven#141]
I use the command palette to create a new Maven project from an archetype.
After selecting the archetype (i.e. the quickstart one), the window for choosing the folder to save the project is opened but it's somehow frozen. I cannot navigate in folders. I can just press ESC to close the window.
My OS is Fedora 28.
Any idea?

**Comment by ppatierno** [comment]
It turned out that if I select the archetype with the mouse, then the folders window is frozen.
If I chose the maven archetype using the up/down arrow and then pressing enter (so using the keyboard) then the folders window is usable.

**Comment by Eskibear** [comment]
I manage to reproduce it on Ubuntu 18.04. 

To get VS Code started, I followed https://github.com/Microsoft/vscode/issues/3451#issuecomment-217716116 to modify a system lib. I don't know whether it's the cause or not. (maybe not)

I think it's more like a VSCode general issue, because here in Maven Extension we simply call the related API. Investigating.

**Comment by Eskibear** [comment]
I've opened an issue. See https://github.com/Microsoft/vscode/issues/62704

**Comment by Eskibear** [comment]
@ppatierno VS Code 1.31.0 has been shipped with the fix. Can you also give it a try see if it works for you?

**Comment by ppatierno** [comment]
@Eskibear sorry to be late. I tested it and now it works, thanks!
