### ISSUE TITLE
[Question / Enhancement] Go to dependency detail

### ISSUE THREAD

**Issue by elminsterjimmy** [microsoft/vscode-maven#216]
Hi there,

Thanks for providing the amazing plugin for VSC.
Is there any possible to have a feature to provide a jump to its dependencies (parent / dependency / plugin)? That will help to go thru the maven dependencies tree.

**Comment by Eskibear** [comment]
Technically it's possible. 
* From effective-pom, groupId/artifactId of parent/dependency/plugin are somehow known.
* Dependencies have been downloaded into your local maven repository, so it's feasible to locate `groupId/artifactId/version/<gid>-<aid>-<version>.pom` 
* With VSCode's API, it's ok to register a [DefinitionProvider](https://github.com/Microsoft/vscode/blob/ccdd2997a66965c7104fe180207d9a710ea50fa5/src/vs/vscode.d.ts#L2225-L2242).

**Comment by elminsterjimmy** [comment]
Thanks @Eskibear

**Comment by Eskibear** [comment]
I tried implementing a POC, it's feasible to find local dependency and do the navigation. But one question is, what should be the best user experience? By clicking to the dependency, what details do you want to see? I find in IntelliJ IDEA, it opens the corresponding pom file in read-only mode. Is that what you want? Or you just need to know the effective version of the dependency?

**Comment by elminsterjimmy** [comment]
It would be better to have the effective version of the dependency / plugin in a hover text or something alike, in most case this is sufficient for an individual dependency, also providing a shortcut for jumping to the corresponding pom is needed for getting more details about the parent dependency or checking the dependencies of specified dependency which are the typically use cases.

**Comment by Eskibear** [comment]
> It would be better to have the effective version of the dependency / plugin in a hover text

Technically it's also feasible to add hover information. Currently by using maven search API, it's easy and fast to get and show the **latest** version of a dependency/plugin. Do you think the latest version is important or helpful?

As for the **effective** version, I think we can first generate effective-pom, and read the corresponding version from that. BUT here is a problem, for some large projects, it's time-consuming, do it in real time is not possible (for the long latency to show hover info). If we generate effective-pom in advance for all projects, it cost high CPU sometimes. (e.g. when I have large number of projects)

> providing a shortcut for jumping to the corresponding pom
In IntelliJ IDEA, it opens the pom in read-only mode. But currently I don't see any API to open the file in read-only mode in VS Code. I think it's important because if user mistakenly modify pomfile of some local artifacts, it will bring unexpected errors which are difficult to resolve.  If your purpose is to find out dependency conflict, I think we can have a new feature to provide better visualization of the dependency tree. What do you think?

**Comment by elminsterjimmy** [comment]
> Technically it's also feasible to add hover information. Currently by using maven search API, it's easy and fast to get and show the **latest** version of a dependency/plugin. Do you think the latest version is important or helpful?

The last version is not so important, the most important part in version is compatibility that needs to find out the **effective** version.

> If your purpose is to find out dependency conflict, I think we can have a new feature to provide better visualization of the dependency tree. What do you think?

Yes, a better visualization of the dependency tree would does huge help, the most desired functionality is to check the dependency tree with all effective version.

**Comment by Massinissab** [comment]
I'm a big fan of Netbeans IDE. 
I think Netbeans has the best maven integration.
In netbeans when you hover on a dependency you can see a tooltip showing you : 

- the group id

- the artifact id

- which the dependency is coming from (the shortest path to the dependency)

You can also right click on a dependency and show its pom file and its dependencies.

**Comment by Eskibear** [comment]
Now you are able to:
- navigate to its pom by ctrl+click the groupid/artifactid/version of a dependency
- hover to see effective version (useful when its version is not defined here)
- view dependencies and conflicts in Maven explorer.
