### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Donathien** [Microsoft/vscode-maven#299]
- Issue Type: `Performance`
- Extension Name: `vscode-maven`
- Extension Version: `0.16.0`
- OS Version: `Windows_NT x64 6.1.7601`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\Tony\vscjava.vscode-maven-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by Eskibear** [comment]
As we just had a new release, it's probably due to extension installation which is out of our control. See more details in https://github.com/Microsoft/vscode-java-pack/issues/81#issuecomment-476457431

If the performance issue **stably** bothers you, feel free to re-open it, and please make sure to **attach the cpuprofile** as mentioned, and we'll proceed to analyse.
