### ISSUE TITLE
Error occurs when executing maven goals

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/vscode-maven#358]
**Describe the bug**
An error occurs when executing maven goals.

**To Reproduce**
1. Clone a maven project
2. Open maven project
3. Execute maven goals

**Results**
![image](https://user-images.githubusercontent.com/41051257/60709104-3bb6bb80-9f42-11e9-8a37-e7541f90d8b9.png)

**Environments (please complete the following information as much as possible):**
 - OS: Windows 10/OS X
 - VS Code version: 1.36.0
 - Extension version: 0.18.0 (buildId=9859256)

**Comment by Eskibear** [comment]
The error log is printed by 
https://github.com/microsoft/vscode-maven/blob/3c36c1eb8cc65a889ad4dccc813400f8e27ccd67/src/utils/historyUtils.ts#L29

It's because the history file doesn't exist. For a project, it should only occur when a command is executed for the first time.

We might not need to print it as it provides no useful info to users.
