### ISSUE TITLE
Hide 'Maven Projects' section when not working on maven projects

### ISSUE THREAD

**Issue by chuck-flowers** [Microsoft/vscode-maven#36]
Whenever I'm working in a folder that doesn't contain a pom.xml or when I don't have a folder open, the 'Maven Projects' section still appears. Can this section be hidden an only shown when a pom.xml file is detected?

**Comment by Eskibear** [comment]
That is also what we want. We had a try before, but it was blocked by the limited VS Code APIs at that time.
Since VS Code has been updating all the time, I'm not sure whether it is feasible now.  
And if you have any information about that (e.g. related API, extension with similar behavior, etc) please kindly share with us.

**Comment by jerryturcios08** [comment]
@Eskibear Is it possible to remove the section by default? I recall having done that before with a different extension, but I am not entirely sure on that.

**Comment by Eskibear** [comment]
@jerryturcios08 As far as I know for the moment, the "Maven Project" section exists as long as you **enable** the extension, before you actually **activate** it. 
Only after activation, the src code in the extension starts working. So theoretically I think it's impossible to perfectly control the visibility, according to my knowledge. 

BTW, as you see in the following image, VS Code handle the visibility of each section by itself. 
![image](https://user-images.githubusercontent.com/2351748/38118321-cfece90a-336e-11e8-9af9-c129e27d81db.png)
 
And you can disable a certain extension in your workspace as a mitigation, so that you can always hide a certain section.
I do want to provide such a feature just as you mentioned, e.g, add a config entry like `defaultVisibility`. So if you have recalled the name of the extension, please kindly let me know.

**Comment by Eskibear** [comment]
fixed in #80

**Comment by marcellourbani** [comment]
Not sure why this is marked as closed, I see it all the time in javascript projects and others.
Should be easy to tie it to a custom context variable

**Comment by Eskibear** [comment]
@marcellourbani see https://github.com/microsoft/vscode-maven/issues/380#issuecomment-519758018
