### ISSUE TITLE
Terminal opens in the wrong workspace root

### ISSUE THREAD

**Issue by anthonyvdotbe** [microsoft/vscode-maven#467]
**Describe the bug**
Given I have 2 workspace roots, A and B, and the editor currently shows a file in A.
When I run a goal on B via `Maven Projects`.
Then the terminal opens in A, instead of the expected B.

**To Reproduce**
1. Open 2 Maven projects with workspace roots A and B
2. Open a file in A
3. In the `Maven Projects` view, run a goal on B
4. Notice that the terminal opens in A (but the terminal's name correctly shows Maven-B)

**Expected behavior**
The terminal opens in B

**Environments**
 - OS: Windows 10
 - VS Code version: 1.42.0
 - Extension version:  0.21.0

**Additional context**
This is related to #68, but, IIUC, that was caused by the fact that all Maven commands were run in the same terminal. Now they're run in different terminals, but don't always open in the correct workspace root.

**Comment by Eskibear** [comment]
Thanks for reporting. We doesn't specify `cwd` when creating a terminal, so it always use the default workspace root as cwd.

https://github.com/microsoft/vscode-maven/blob/b427c38b3f3938a3e5d71fc91101ec63525475d5/src/mavenTerminal.ts#L24

I can simply change it to open workspace root of the target project. Is that what you expect? BTW, will it be better if the `cwd` is set to the project folder instead of the workspace root?

**Comment by anthonyvdotbe** [comment]
> I can simply change it to open workspace root of the target project. Is that what you expect?

Yes, that's what I'd expect.

> BTW, will it be better if the cwd is set to the project folder instead of the workspace root?

No, I believe it should always open in the workspace root, because there's only 1 terminal per workspace root, and so for consistency, it should always open there (and once #451 is done, this wouldn't add value anyway).

**Comment by Eskibear** [comment]
Ok, for now I'll set it to workspace root of the target project.
