### ISSUE TITLE
Maven: Create Maven Project - Destination Folder is ignored

### ISSUE THREAD

**Issue by dclaze** [microsoft/vscode-maven#478]
## Steps to reproduce
1. CMD + SHIFT + P
2. Type: `Maven: Create Maven Project`
3. `Select an archetype ...` > `archetype-quickstart-jdk8`, `Select version ...` > `1.2.0`
4. Choose `Destination Folder` (eg. /users/<alias>/<project>)
5. Follow wizard for input in Terminal
    - `groupId`
    - `artifactId`
    - `package`
    - `Y`
6. Maven package is created `/Users/<alias>/.vscode/extensions/vscjava.vscode-maven-0.21.1/resources/maven-wrapper/<project>`

## Expected
Step 6 creates project inside `Destination Folder` specified at Step 4

## Actual
Step 6 creates project inside `/Users/<alias>/.vscode/extensions/vscjava.vscode-maven-0.21.1/resources/maven-wrapper/<project>`

**Comment by Eskibear** [comment]
Yes I can reproduce it with (powershell + maven 3.6.2), param `-DoutputDirectory` just doesn't work.

BTW can you paste below information here, see if your case is the same: 
1. shell in terminal, e.g. CMD? PowerShell? GitBash?...
2. full command that the extension sent to terminal (chech if ` -DoutputDirectory=xxx` exists)
3. maven distribution version (since it's fallback to the embedded wrapper, it should be 3.6.2)

**Comment by Eskibear** [comment]
By adding `-X` for verbose info, I find that it's using `maven-archetype-plugin@3.0.1`, and I was wondering if it's bug of the plugin. By explicitly specifying the plugin version, i.e. using `maven-archetype-plugin@3.1.2`, I managed to create project in the expected place. 

So I'm either
* Update version of the embedded maven wrapper, see if it brings the latest archetype plugin in..
or 
* explicitly using archetype@3.1.2 in commandline

**Comment by Eskibear** [comment]
The fix will be shipped in the next version. For the moment, you can replace `archetype:generate` with `org.apache.maven.plugins:maven-archetype-plugin:3.1.2:generate` in your full command, see if it can create the project in the correct folder.
