### ISSUE TITLE
maven.executable.options not overridable in workspace settings

### ISSUE THREAD

**Issue by jahan01** [microsoft/vscode-maven#524]
**Describe the bug**
maven.executable.options is not overridable in workspace settings.
ceb1aba558e2c377972536227cb0dbdad7baafa2 has changed the scope from `resource` to `machine`. 

I presume it was meant to be `machine-overridable` ? This will allow us to override in workspace or folder settings.

**Expected behavior**
maven.executable.options is overridable in workspace (or) folder settings

**Comment by Eskibear** [comment]
For security concern, it was intended to become `machine`, in order to **disallow** you to override in workspace settings.

`maven.executable.options` will be directly appended to the command you execute. Suppose there is a malicious repository, with a malicious command injected in `.vscode/settings.json`, then you clone the repo, run a maven goal, and the malicious command will be executed. 

It does bring some inconvenience, and we are considering if there would be a better solution or a compromising approach. Let us know if you have any idea.

**Comment by jahan01** [comment]
thanks for explaining, I understand the security concern here.

vscode core has `Terminal: Manage Workspace Shell Permissions` to mitigate this class of problems for shell settings included in workspace code. User has to explicitly permit to allow workspace settings change the shell settings. This permission is given once per workspace.

Perhaps may be something similar to this will help ?

**Comment by Eskibear** [comment]
Thanks for the info, that makes sense.  We are also adopting the similar approach for "whether to use maven wrapper in this workspace" (#526).

And the scope of "maven.executable.options" has been changed to `machine-overridable`.
