### ISSUE TITLE
This setting can only be applied in user settings in local window or in remote settings in remote window

### ISSUE THREAD

**Issue by hukaixuan2017** [microsoft/vscode-maven#539]
**Describe the question**

we want to build a java development environment on linux, use maven to menage java jar package .

I import the java project, the jdk evnviroment was configured and the following error occurred when download the jar package with mavn。

![image](https://user-images.githubusercontent.com/29294119/94092478-78bfe400-fe4d-11ea-995e-cbe2167f1332.png)

it seems that this setting does not support linux ?

![image](https://user-images.githubusercontent.com/29294119/94093149-1b2c9700-fe4f-11ea-96e4-57550fe2285c.png)

**Expected behavior:**

maven can be download jar package.

**Environments (please complete the following information as much as possible):**

- OS: Linux
- VS Code version: May 2020 (version 1.46)
- Extension version: Maven for Java 0.24.2

**Comment by Eskibear** [comment]
From the screenshot, I guess you are using VS Code Remote, and your workspace is in a container. And the `settings.json` is under `<workspaceRoot>/.vscode`, right?

For security concern, `maven.executable.path` can only be set in a) User settings or b) Machine/**Remote** settings.  The settings.json you opened is for "workspace settings". 

Open Settings, choose the correct scope, see below
![image](https://user-images.githubusercontent.com/2351748/94095427-4a91d280-fe54-11ea-91d8-14e5d53def23.png)

**Comment by hasanmhsh** [comment]
The problem is that you are trying to set settings on your local vscode while you are connecting remotely with other code server
So you need to open settings for remote code server rather
Open command palette : CTRL + SHIFT + P
Type settings command then select remote settings (json)
![image](https://github.com/microsoft/vscode-maven/assets/47121336/75d38cea-4c1a-4682-a29c-c1ab49745098)
Then edit settings as you prefer
