### ISSUE TITLE
/bin/bash: mvn: command not found

### ISSUE THREAD

**Issue by oli-unreal** [microsoft/vscode-maven#545]
**Describe the bug**
When I run a maven task in a devcontainer, I always get: 
```
> Executing task: mvn -B verify <

/bin/bash: mvn: command not found
The terminal process "/bin/bash '-c', 'mvn -B verify'" failed to launch (exit code: 127).
```
But the mvn is accessible via the command line, `mvn -B verify` works fine in bash.

**To Reproduce**
1. Create a java devcontainer with maven (I used the sample: https://github.com/microsoft/vscode-remote-try-java)
2. Create a maven task (the default one for example)
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "verify",
            "type": "shell",
            "command": "mvn -B verify",
            "group": "build"
        },
    ]
}
```
3. Run the task

**Expected behavior**
The task should have the same behavior as the bash.

**Environments (please complete the following information as much as possible):**
 - OS: Windows 10
 - VS Code version: 1.50.1
 - Extension version [e.g. 0.9.0]
 - Using devcontainer
- Using wsl 2

**Additional context**
Maven is in the $PATH:
`/usr/local/sdkman/candidates/maven/current/bin:/home/vscode/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/bin:/usr/local/share/nvm/current/bin:/usr/local/openjdk-11/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/sdkman/java/current/bin:/usr/local/sdkman/maven/current/bin:/usr/local/sdkman/gradle/current/bin:/home/vscode/.local/bin`
and in the maven.executable.path

**Comment by Eskibear** [comment]
I'm not quite familiar with devcontainer, but here are some tips to dig out the root cause. 

> /bin/bash: mvn: command not found

When you run `mvn` in bash, it searches $PATH for the binary. No doubt, bash cannot find `mvn` in $PATH , so we should verify the actual value of $PATH. For example you can:

```
"command": "mvn -B verify",

 # change it to

"command": "echo $PATH",

# and re-run the task to see output
```


> maven.executable.path

This setting is provided by Maven extension. If you run maven commands from the extension, it takes effect. On bottom left, you'll see "Maven" explorer, that's the entry.

The "task" you run is a common vscode feature, basically you can fill in anything in "command", then it's not related to Maven.

**Comment by oli-unreal** [comment]
The $PATH in the task was indeed not the same as the one in bash.
To make the tasks work I forced the PATH
```json
{
    "version": "2.0.0",
    "options": {
        "env": {
            "PATH": "/usr/local/sdkman/candidates/maven/current/bin:${env:PATH}"
        }
    },
    "tasks": [...]
}
```
Also running from the "Maven" explorer works fine.
Thanks for you help
