### ISSUE TITLE
set keybinding for maven compile

### ISSUE THREAD

**Issue by wjx0912** [microsoft/vscode-maven#546]
![1](https://user-images.githubusercontent.com/5556482/97824555-39f83600-1cf7-11eb-8be8-ae4a02503472.png)

i set the keybing  " ctrl + F7"  for maven compile, it show "pompath not defined",  i find no valid information on google.

how to set the shortcut?

thanks.

**Comment by Eskibear** [comment]
`maven.goal.compile` requires an argument to specify the target Maven project, otherwise it has no idea which project you are going to compile. 

However the command is not designed for such use case, thus the argument is an object instead of a plain string. If you do want to use a keybinding, pass the absolute path in `args`. e.g
```json
[
  {
    "key": "ctrl+f7",
    "command": "maven.goal.compile",
    "args": {
      "pomPath": "C:\\<path-to-pom>\\pom.xml"
    }
  }
]
```

**Comment by Eskibear** [comment]
let me know if it works for you.

**Comment by wjx0912** [comment]
@Eskibear  
it works, thank you very much.
