### ISSUE TITLE
[question/beginner] skip archetype selection (the quickstart archetype is using a very old Java)

### ISSUE THREAD

**Issue by aderchox** [microsoft/vscode-maven#577]
I don't know deeply about Maven so apologize in advance if this question is silly, but I use Maven as a build tool and also as a standard project's hierarchy generator, so I generate new projects using the "quickstart archetype", but it's using such an old version of java(version 1.7), why?! It might be irrelevant to this extension but the maven plugin in eclipse allows skipping the archetype selection step. Currently I have to start the project and then edit the pom.xml and edit these versions to a newer version(e.g. 15) and reload the project, otherwise some features such and lambdas and etc. won't work:
```
<properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.7</maven.compiler.source>
    <maven.compiler.target>1.7</maven.compiler.target>
</properties>
```
Are these necessary at all(similar to how groupId, artifactId, dependencies and etc. are strictly necessary)?
Is it possible to skip these properties? Or maybe I'm having a fundamental misunderstanding here?

**Comment by Eskibear** [comment]
For the moment, this extension only helps you to assemble the long command and send it to terminal. The project was generated from the archetype you selected.

> but it's using such an old version of java(version 1.7), why?!

The content is generated by `maven-quickstart-archetype`, see https://maven.apache.org/archetypes/maven-archetype-quickstart/index.html

> Currently I have to start the project and then edit the pom.xml and edit these versions to a newer version(e.g. 15) and reload the project, otherwise some features such and lambdas and etc. won't work

You can use other archetypes (defaults to Java 8 or above) to genreate your project, instead of `maven-quickstart-archetype`. Or create your own archetype. 


> Is it possible to skip these properties?

See https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-source-and-target.html
