### ISSUE TITLE
Environment Variables not set

### ISSUE THREAD

**Issue by tranky82** [microsoft/vscode-maven#637]
**Describe the bug**
Maven for Java don't use environment variables set in maven.terminal.customEnv neither clicking "Show Dependencies" nor "Show Effective POM". It works clicking on the other options.

Setting "JAVA_HOME" environment variable, the output is:
```
The JAVA_HOME environment variable is not defined correctly 
This environment variable is needed to run this program 
NB: JAVA_HOME should point to a JDK not a JRE 
```

**To Reproduce**
1. Go to 'Explorer'
2. Expand 'MAVEN' section
3. Right Click on a Maven project
4. Select "Show Dependencies" or "Show Effective POM"

**Expected behavior**
Setting "JAVA_HOME" environment variable into "maven.terminal.customEnv" on "settings.json" file should be affect the opened output window.
I printed "JAVA_HOME" within mvn.cmd and the output is an empty string.

My settings.json section:
```json
  "maven.terminal.customEnv": [
    {
      "environmentVariable": "JAVA_HOME",
      "value": "C:\\Software\\Java\\jdk1.8.0_181_x64"
    }
  ]
```

**Environments:**
 - OS: Windows 10
 - VS Code version: 1.56.2
 - Extension version: 0.30.1

**Screenshots**
settings.json:
![image](https://user-images.githubusercontent.com/2782448/119239980-23a7af80-bb4d-11eb-8849-606e9b11ae45.png)
Maven Explorer right click menu:
![image](https://user-images.githubusercontent.com/2782448/119239898-a419e080-bb4c-11eb-8dcd-6d0bd5f21c66.png)
Maven for Java output window:
![image](https://user-images.githubusercontent.com/2782448/119239937-e511f500-bb4c-11eb-953d-1b6e60321d21.png)

**Comment by Eskibear** [comment]
maven.terminal.customEnv | Specifies an array of environment variable names and values. These environment variable values will be added to the terminal session before Maven is first executed.
-- | --






`maven.terminal.customEnv` only affects **terminals**. Sorry for the inconvenience. 
As a workspace level setting, custom environment is intentionally disabled for the commands you mentioned, to fix the security issue related to malicious code injection. 

It can be completely resolved after vscode releases its workspace trust feature. If user explicit choose to trust the workspace, we can load workspace setting for above commands. See https://github.com/microsoft/vscode/issues/106488

A workaround is, you set a system wide JAVA_HOME for maven, or launch VS Code with JAVA_HOME set.

**Comment by tranky82** [comment]
Ok, I undestand your explanation, thank you, i'm going to try the workaround you wrote.

What is not clear is why does the other commands (clean, install, package, compile, validate, ...) are allowed to be executed on the terminal and why the other two aforementioned don't: "Show Dependencies" and "Show Effective POM".

What's the difference beetween these two kind of commands?

Thank you in advance for your time.

**Comment by Eskibear** [comment]
> What's the difference beetween these two kind of commands?

Dependenies and effective pom are calculated by executing maven commands in **background process**. Other commands like clean, install..., we simply construct the commands and **send them directly to vscode's terminal**. Strictly speaking, both have the security issue.

Because previously effective pom was **automatically** calulated on startup, in order to prefetch informations like plugins. To fix the that issue (having more impact), we simply removed custom envs support for all background process based features.

Ideally, we should do the same thing for background processes and terminal commands, dismiss workspace-level custom envs for untrusted workspaces. If VS Code ship workspace trust feature in next release, we will fix it based on that. If not, I'll disable related workspace-level settings for all workspace, and the side effect is we lose the flexibility as https://github.com/microsoft/vscode-maven/issues/524 .
