### ISSUE TITLE
根据pom.xml创建.classpath&.project文件需要多次重启VSCode

### ISSUE THREAD

**Issue by mainxx** [Microsoft/vscode-maven#64]
我因错误修改了.classpath，导致项目无法运行。
接下来，我把.classpath以及.project删除了。
然后重启。vscode会根据pom.xml生成.classpath跟.project文件
但是重启，仅仅生成了.project文件。
第二次打开的时候。生成了.vscode\launch.test.json。并没有生成.classpath文件。
第三次打开会生成.classpath但是无法运行我的单元测试.
第四打开就完全可以了。

**Comment by Eskibear** [comment]
Thanks for reporting the issue. 
This extension vscode-maven is not responsible for building a maven project. It's built by [vscode-java](https://github.com/redhat-developer/vscode-java) using m2e, that's why you got `.project` and `.classpath` files.

I just reproduced it and created an issue in the [right place](https://github.com/redhat-developer/vscode-java/issues/558), where you can track the latest status.

**Comment by mainxx** [comment]
THX...

**Comment by Eskibear** [comment]
@mainxx 
I tried several ways to fix the issue in eclipse.jdt.ls, none of them is perfect without side effects. Still investigating. 

And following is a manual workaround that can temporarily unblocks you for the moment. 
1. Reload window. 
2. Right click on `pom.xml`, select `Update project configuration`.
![image](https://user-images.githubusercontent.com/2351748/42300543-90ad25b2-8043-11e8-8e81-1e40d14a26b6.png)
3. It actually will re-import the maven project according to `pom.xml`, and re-generate `.classpath` file

**Comment by donraj** [comment]
Thanks it is a life saver!
