### ISSUE TITLE
[Warning] Cannot register 'maven.executable.path'

### ISSUE THREAD

**Issue by Melody618** [microsoft/vscode-maven#657]
**Describe the warning**
In the debugger mode, when opening a new maven project, there pops up a warning saying "[vscjava.vscode-maven]: Cannot register 'maven.executable.path'. This property is already registered."
![image](https://user-images.githubusercontent.com/25446374/125763391-cfa77038-6f7f-46b8-8288-40053bcaa22d.png)

messages from call stack:
![image](https://user-images.githubusercontent.com/25446374/125763905-42b3283d-6b88-434d-bc8b-44d2b079be9d.png)

It may be a vscode issue, open the issue here to track.

**Environments:**
 - OS: Windows 10
 - VS Code version: 1.58.1
 - Extension version: 0.31.0

**Comment by ZigZag59** [comment]
Hello,

I have the same issue and the Maven Explorer is not available anymore.
![MavenExplorerNotAvailable](https://user-images.githubusercontent.com/46565570/146046164-1bb2b51d-1080-46b0-8e58-28f261e7925c.png)
By opening the extension, I can see the same error message : Cannot register 'maven.executable.path' This property is already registered.
![MavenForJavaNotActivated](https://user-images.githubusercontent.com/46565570/146046711-2e1b7c64-9227-478a-8d5e-c32c106ce8db.png)

As a workaround, I have to execute the command : `Java: Clean Java Language Server Workspace`.

**Environments:**
- Version : 1.63.0 (user setup)
- Validation : 7db...77e
- Date : 2021-12-07T06:26:56.179Z
- Electron : 13.5.2
- Chromium: 91.0.4472.164
- Node.js : 14.16.0
- V8 : 9.1.269.39-electron.0
- Système d’exploitation : Windows_NT x64 10.0.19043
- Maven for Java : v0.34.1

**Comment by Eskibear** [comment]
It's strange. It should has nothing to do with the command `Java:  Clean Java Language Server Workspace`. Are you debugging a vscode extension, or simply developing a Maven project?

If you have way to stably reproduce it, please let us know. And if you happen to reproduce it, please check `Output -> Log(Extension Host)`, and attach the logs here, so we can investigate if there's anything wrong with the extension activation order.

**Comment by ZigZag59** [comment]
Hi @Eskibear ,

I'm developing Maven project and I would even say several Maven projects. 
It seems the problem occurs when I have multiple instances of vscode on different Maven projects.

The "maven.executable.path" property is not defined neither in the workspace (.vscode\settings.json), nor in the user settings (%AppData%\Roaming\Code\User\settings.json).
I updated vscode yesterday to 1.63.1 but the issue is always active

Below the log of Extension Host:

[ExtensionHost.log](https://github.com/microsoft/vscode-maven/files/7720686/ExtensionHost.log)

**Comment by Eskibear** [comment]
With this error, can you still use features from Maven extension, e.g. browse your projects in "Maven" explorer?

From logs I find:
> [2021-12-15 16:10:35.427] [exthost] [info] Not activating extension 'vscjava.vscode-maven': Timed out while searching for 'workspaceContains' pattern **/pom.xml

Maven extension was not successfully activated due to the timeout. AFAIK, VS Code introduced a `7s` timeout for `workspaceContains` (see https://code.visualstudio.com/updates/v1_63#_timeout-of-workspacecontains ). I'm wondering how large/deep your Maven project is, so that it failed to find a `pom.xml` file in 7s.


> It seems the problem occurs when I have multiple instances of vscode on different Maven projects.

I cannot reproduce it. But based on your log, I believe it should be related to extension activation.

> The "maven.executable.path" property is not defined neither in the workspace

It doesn't matter whether you've set the value. The error message was probably telling that Maven extension failed to register the setting entry into VS Code, because the setting entry has already been registered before (probably during some unwanted/malformed activation process).

**Comment by ZigZag59** [comment]
HI,

You have identified the origin of the issue. In my opinion, the "info" level is too low. I would rather have used the level "warning". Maybe for a next issue on vscode with the possibility of configuring the timeout.

Whenever the timeout error occurs I don't have the extension enabled and therefore I don't have maven explorer.

To reproduce it, it's easy with "Microsoft Teams" :D . Start a meeting and start at least 2 vscode instances. As I'm on remote, I have always Teams up and it is very resource intensive.

Thank you for the diagnostic and I think you can close this issue.
