### ISSUE TITLE
Conflict tree item is not highlighted

### ISSUE THREAD

**Issue by Eskibear** [microsoft/vscode-maven#672]
Open https://github.com/spring-projects/spring-petclinic , expand dependencies node.

Why is `org.webjars:jquery:2.2.4` not highlighted? In this case with only the conflict items, how do I find out where 2.2.4 is?

![image](https://user-images.githubusercontent.com/2351748/127086931-2eada62d-5e10-4d1e-aeb2-3b6888ed0ae3.png)

**Comment by Melody618** [comment]
> Why is `org.webjars:jquery:2.2.4` not highlighted?

Only items that are omitted for conflict are highlighted. It means potential warning. `org.webjars:jquery:2.2.4` is an effective dependency but not an omitted one.

> In this case with only the conflict items, how do I find out where 2.2.4 is?

It is a good question. And where 2.2.4 is introduced is important information to resolve conflicts. But highlighting is not a good way. Because it may pollute the whole view and bring misunderstandings.  We are still working for a better way. 
There is a workaround here. VS Code provides filtering on every explorer. When you focus on Maven explorer, you can type keywords directly to filter all items. In this case, you can type `jquery` to filter and find where 2.2.4 is.

**Comment by Eskibear** [comment]
filtering only applies on expanded items, and there's no API to add filters programmatically for the moment. 

An option is, we add a command (e.g. go to conflict) to expand the first conflict item. In the case above, we 1) find an 2.2.4 item, 2) expand all parents, 3) focus on it.

**Comment by Melody618** [comment]
have tried a **go-to-effective** command to expand the only one effective item by `treeView.reveal()`. In the case above, we 1) find the 2.2.4 item, 2) expand all parents, and 3) focus on it.

problems remain: 
1) if there are dependencies with several different versions (e.g. 2.5, 2.6, 2.7), how to go-to-next, or go-back-to-conflict
2) when using **go-to-effective ->exclude** way to resolve conflict, need to repeat this action several times until no other versions are in the tree. Thus, set-version-to is a better method for resolving conflicts.

**Comment by Eskibear** [comment]
closed by #716
