### ISSUE TITLE
Save Custom Goals

### ISSUE THREAD

**Issue by JustAnotherSoftwareDeveloper** [Microsoft/vscode-maven#72]
My default workflow is to run "clean install". To do this I have to do the following things

1) Open the command prompt and navigate to "Maven: Run Goal"

2) Select Project

3) Either a) Select the custom goal from history OR b) select custom goal and write it again

It would benefit me to have a way to save off custom goals in a way that they are treated as "first class citizens" IE accessed in a way similar or identical to the standard goals ("install, deploy") are

**Comment by Eskibear** [comment]
Exactly, I have similar default workflow "clean package", and that's why we register the command `maven.history`, it allows me to fast re-run the workflow.

For entries in the context menu as shown below, they are defined in `package.json` [here](https://github.com/Microsoft/vscode-maven/blob/master/package.json#L47).
![image](https://user-images.githubusercontent.com/2351748/42547160-5639825e-84f3-11e8-8550-5ac081c4ee2e.png)
For the moment, I don't think VS Code has such APIs to dynamically add new commands. 
Ref: https://github.com/Microsoft/vscode/issues/1422

For the items in QuickPick box shown below, currently we directly leverage those pre-defined command I mentioned above. Code is [here](https://github.com/Microsoft/vscode-maven/blob/master/src/ProjectDataProvider.ts#L189)
![image](https://user-images.githubusercontent.com/2351748/42547434-a9af8dba-84f4-11e8-8b65-3c2d5457a52a.png)
For this part, technically it's doable. E.g. read from part of settings and append new items to the list, then execute as custom goals.

But I'm wondering that is `Maven: history` not good enough for your scenario? By **command palette** -> *Maven: history* -> *select the clean install one*, you don't even have to select the project in an extra step. Please kindly share your experience about it.

**Comment by JustAnotherSoftwareDeveloper** [comment]
Let's be clear: **What you've done already is awesome**. I can more or less use this for my every day workflow. However, there are reasons that the maven history command alone is not enough for me. 

I work on a variety of different maven projects in different workspaces. Each time I open a new project, I have to re-enter the list of custom commands I use for the new project. 

If possible, it would nice to have a section in the settings section defining a list of goal names and their commands. At which point those could appear as options in the context menu for whenever you activate "custom goals", even if you haven't ran that goal on the particular maven project you're referencing. I believe that solution would be compatible with the current vscode api.

**Comment by Eskibear** [comment]
I remember we've refactored a lot and removed command palette entry for a lot of commands (such as maven: install ) in order to decrease noise. Following is what I have now. 
![image](https://user-images.githubusercontent.com/2351748/43042249-5cf369f0-8dab-11e8-8d8d-8c5274f3428b.png)

@JustAnotherSoftwareDeveloper Let's first figure out what's the version of the extension you are using?

**Comment by JustAnotherSoftwareDeveloper** [comment]
I'll have to check when I get into work on monday. It's most likely that I'm on the right version, and simply misremembered the command pallet name. Either way, I'll review my workstation Monday so I can provide a more concise suggestion.

**Comment by Eskibear** [comment]
And back to the place to put pre-defined commands, for the latest version of the extension, following place is somehow feasible.
Maven: Execute commands -> select a project -> HERE we can append the pre-defined commands to the dropdown list.

**Comment by JustAnotherSoftwareDeveloper** [comment]
While I initially suggested a dropdown option, I'm not tied to it. If there was a "Maven: Execute User Defined Command" (or something with the same functionality but a better name) that listed commands defined in the settings, that would be more than enough to fit my use case. 

I guess it comes down to the difficulty of implementation and what would provide the best User Experience.

**Comment by Eskibear** [comment]
@JustAnotherSoftwareDeveloper Now in v0.15.0, you are able to set "favorite" command via config entry "maven.terminal.favorites".
