### ISSUE TITLE
Launching a Maven goal using debug always fails to connect to the debugging port

### ISSUE THREAD

**Issue by Artur-** [microsoft/vscode-maven#757]
**Describe the bug**
Right clicking on "jetty / run" in the Maven window and selecting "Debug" always fails with
![image](https://user-images.githubusercontent.com/260340/140334093-a42432f5-5aac-47a2-9ebd-d3ecba1861d6.png)

The reason is that it tries to connect to the launched process before the process is listening on the debug port

If you have a .class file open while launching the target, you will hit the bug described in #745  but this dialog actually prevents the connection from happening too early so it functions as a bad workaround...

**To Reproduce**
1. Clone https://github.com/vaadin/flow
2. Run `mvn install -DskipTests`
3. Open `flow-tests/test-root-context` in VS Code
4. Launch jetty:run using `Debug`

Probably this can be reproduced in much simpler projects also

**Expected behavior**
Launching using "debug" always works

**Environments (please complete the following information as much as possible):**
 - OS: mac Big Sur
 - VS Code version: 1.61.2
 - Extension version 0.34.1

**Screenshots*

https://user-images.githubusercontent.com/260340/140335328-2a1f5043-b26b-4e7d-a477-b303be452d88.mov

**Comment by Eskibear** [comment]
> prevents the connection from happening too early 

That's the key. The extension execute a Maven command and asks Java debugger to attach after a 1000ms delay. Increasing this magic number would probably mitigate your issue, but wouldn't solve the problem perfectly.

The problem is, this extension has no knowledge about when maven process starts to listen on the port.

**Comment by Artur-** [comment]
I see, could it either try a few times or then scan the output for the "listening for transport" part?

**Comment by Eskibear** [comment]
https://github.com/microsoft/vscode-maven/blob/1aab551220fdc03c6e85e9813f167dc9db5b6ca7/src/handlers/debugHandler.ts#L59-L62

In currently mechanism, it simply asks terminal to run the command, and asks the debugger to attach, with no capability to further track the status...

However, it might be possible to run the maven command as a `Task`, then we might be able to check the output. But that would require some investigation about VS Code's [Task API](https://code.visualstudio.com/api/references/vscode-api#tasks).

**Comment by Artur-** [comment]
Ah but with knowledge of the port number, that could be polled say every 500ms until it is up

**Comment by Eskibear** [comment]
fixed, will be shipped in next release.

**Comment by loupmasneri** [comment]
I have the same issue on the latest version of vscode/macos:
```
Version: 1.89.1 (Universal)
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:14:24.611Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0
```

**Comment by Eskibear** [comment]
https://github.com/microsoft/vscode-maven/blob/6a90eac5fa0e0374f83742471ef0efe22b3a9979/src/handlers/debugHandler.ts#L61-L73

@loupmasneri
AFAIK current mechanism is to try connecting the target port every 100ms until the 10s timeout. Was it taking longer than 10s to launch your program? If so, we probably want to either a) make the timeout configurable, or b) see if we can use a event driven mechanism instead of polling the port.

@testforstephen will follow up.
