### ISSUE TITLE
Failed to calculate Effective POM. Please check output window 'Maven for Java' for more details.

### ISSUE THREAD

**Issue by FattyPoh** [microsoft/vscode-maven#807]
I'm new in programming, whenever I try to access java fx from the maven tab in file explorer, this message shows up.

**Comment by Eskibear** [comment]
View -> Output -> Select "Maven for Java", see what's in the detailed logs.

**Comment by negwu01** [comment]
Had this issue to raise as well and after view -> output -> select 'Maven for Java',  I got:
```
Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain
Caused by: java.lang.ClassNotFoundException: org.apache.maven.wrapper.MavenWrapperMain
```

**Comment by Eskibear** [comment]
@negwu01 check `.mvn` folder see if your maven wrapper is complete. Usually the error message occurs when maven-wrapper.jar is missing.
Or you can use your local maven executable (if installed) instead of the wrapper by [settings](https://github.com/microsoft/vscode-maven#settings) `maven.executable.preferMavenWrapper` and `maven.executable.path`.

**Comment by AleLeonMarin** [comment]
I got this problem, I when to output -> Maven for Java and says this 
Error: Could not find or load main class org.codehaus.plexus.classworlds.launcher.Launcher
Caused by: java.lang.ClassNotFoundException: org.codehaus.plexus.classworlds.launcher.Launcher

I'm linux user btw
